### PR TITLE
Here is a script which installs Libimobiledevice on OS X & Linux

### PR DESCRIPTION
**Pull request by matteyeux**

### CODE REVIEW

**Comment by mxms0** [comment]
Unsure about the organization about these resources. Will accept request once this is figured out. Perhaps we want a scripts dir and a formal organization.

**Comment by kpwn** [comment]
Hey,
I suggest you put your files in "resources/scripts/Install libimobiledevice/".

Other than that, thanks for contributing.

**Comment by matteyeux** [comment]
Can I add a script which build XPwn ? 
Thank you for this project 🙃

**Comment by kpwn** [comment]
Sure.
I'm sorry, could you please use resources/scripts/ as folder rather than Tools/? It would probably work better.

Thanks.

**Comment by kpwn** [comment]
Sure. Use a similar naming scheme.

**Comment by matteyeux** [comment]
Ok !

**Pull request merged**
